plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
    id 'maven-publish'
}

version = '2.0.0-1.21.4'
group = 'com.ft.helper'

base {
    archivesName = 'FTHelper-GUI-FunTime-1.21.4'
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.4"
    mappings "net.fabricmc:yarn:1.21.4+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.10"     // <-- ДОБАВЛЕНО
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.114.0+1.21.4"
}

loom {
    // ничего особенного не нужно, но блок полезен для модов
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
